server:
  port: 11000

spring:
  application:
    name: spring-cloud-gateway-demo
  cloud:
    gateway:
      # 开启 Gateway 服务注册中心服务发现
      discovery:
        locator:
          enabled: true
      routes:
        - id: csdn-service
          uri: https://blog.csdn.net
          predicates:
            - Path=/csdn

# Eureka Server 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug