server:
  port: 11000

spring:
  application:
    name: spring-cloud-gateway-demo
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

# Eureka Server 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug